---
role:
  pkg:
    - name: rust # rustup-init
      os: ["darwin"]
  install:
    # https://www.rust-lang.org/en-US/other-installers.html
    - command: curl https://sh.rustup.rs -sSf | sh -s -- -y # --no-modify-path
      os: ["!darwin"]
  post_install:
    # TODO rustup help completions
    # Bash:       $ rustup completions bash > /etc/bash_completion.d/rustup.bash-completion
    # Bash(brew): $ rustup completions bash > $(brew --prefix)/etc/bash_completion.d/rustup.bash-completion
    # Zsh:        $ rustup completions zsh > ~/.zfunc/_rustup; fpath+=~/.zfunc
    - shell: /bin/bash
      command: |
        PATH="$PATH:$HOME/.cargo/bin" # . ~/.profile
        rustc --version
        cargo --version
    # - rustup self update
  # env:
  #   RUSTUP_HOME: ~/.rustup
  #   CARGO_HOME: ...
