---
role:
  pkg:
    - name: rust
      os: ["darwin"]
  install:
    # https://www.rust-lang.org/en-US/other-installers.html
    - command: curl https://sh.rustup.rs -sSf | sh -s -- -y # --no-modify-path
      os: ["!darwin"]
  post_install:
    - |
      source ~/.profile # Add "$HOME/.cargo/bin" to PATH
      rustup help completions
      # Bash: $ rustup completions bash > /etc/bash_completion.d/rustup.bash-completion
      # Bash (brew): $ rustup completions bash > $(brew --prefix)/etc/bash_completion.d/rustup.bash-completion
      # ZSH: $ rustup completions zsh > ~/.zfunc/_rustup; fpath+=~/.zfunc
      rustc --version
      cargo --version
  # env:
  #   RUSTUP_HOME: ~/.rustup
  #   CARGO_HOME: ...
