---
role:
  pkg:
    - name: rust
      os: ["darwin"]
  install:
    - command: curl https://sh.rustup.rs -sSf | sh -s -- -y # --no-modify-path
      os: ["!darwin"]
  post_install:
    - rustup help completions
    # Bash: $ rustup completions bash > /etc/bash_completion.d/rustup.bash-completion
    # Bash (brew): $ rustup completions bash > $(brew --prefix)/etc/bash_completion.d/rustup.bash-completion
    # ZSH: $ rustup completions zsh > ~/.zfunc/_rustup; fpath+=~/.zfunc
  # env:
  #   RUSTUP_HOME: ~/.rustup
  #   CARGO_HOME: ...
